var facts = [
  {year:1415, event:"The Battle of Agincourt."},
  {year:1431, event:"Joan of Arc is executed by burning."},
  {year:1433, event:"Zheng He undertakes his seventh and final voyage."},
  {year:1440, event:"Johannes Gutenberg invents the printing press."},
  {year:1453, event:"The Ottomans conquer Constantinople."},
  {year:1478, event:"The Spanish Inquisition is established."},
  {year:1487, event:"The House of Lancaster defeats the House of York in the War of the Roses."},
  {year:1492, event:"Ferdinand and Isabella conquer Granada and officially end the Reconquista."},
  {year:1492, event:"Christopher Columbus sails the ocean blue."},
  {year:1494, event:"The Treaty of Tordesillas."},
  {year:1503, event:"Leonardo da Vinci paints the Mona Lisa."},
  {year:1512, event:"Michelangelo finishes painting the cieling of the Sistine Chapel."},
  {year:1517, event:"Martin Luther posts his 95 Theses."},
  {year:1519, event:"Hernan Cortes lands in Yucatan to conquer the Aztec Empire."},
  {year:1520, event:"The reign of Suleiman the Magnificent begins."},
  {year:1529, event:"The Siege of Vienna."},
  {year:1529, event:"Francisco Pizarro receives royal approval to conquer the Inca Empire."},
  {year:1533, event:"Henry VIII severs ties with the Catholic Church."},
  {year:1555, event:"The Peace of Augsburg establishes 'his region, his religion.'"},
  {year:1582, event:"Oda Nobunaga commits seppuku in Kyoto after a coup d'etat."},
  {year:1587, event:"Mary, Queen of Scots is executed."},
  {year:1588, event:"England defeats the Spanish Armada."},
  {year:1590, event:"The Roanoke Colony vanishes."},
  {year:1597, event:"William Shakespeare publishes Romeo and Juliet."},
  {year:1605, event:"Guy Fawkes attempts his gunpowder treason."},
  {year:1606, event:"The first recorded landfall by a European on Australian soil."},
  {year:1607, event:"The first permanent English settlement of Jamestown is established in America."},
  {year:1618, event:"The Defenestration of Prague begins the Thirty Years War."},
  {year:1626, event:"Gian Lorenzo Bernini begins work on St. Peter's Basilica."},
  {year:1633, event:"Galileo Galilei is sentenced to house arrest for proving heliocentrism."},
  {year:1636, event:"Harvard College is founded."},
  {year:1642, event:"The English Civil War begins."},
  {year:1648, event:"The Treaty of Westphalia ends the Thirty Years War."},
  {year:1649, event:"Charles I of England is executed."},
  {year:1653, event:"Oliver Cromwell becomes Lord Protector of England."},
  {year:1666, event:"The Great Fire of London."},
  {year:1676, event:"Bacon's Rebellion."},
  {year:1682, event:"Versailles becomes the seat of power for the French monarchy."},
  {year:1688, event:"The Glorious Revolution."},
  {year:1692, event:"The Salem Witch Trials begin."},
  {year:1701, event:"Frederick I becomes the first King of Prussia."},
  {year:1703, event:"Forty-seven ronin are ordered to commit seppuku by the shogun."},
  {year:1707, event:"The Act of Union is passed, joining England and Scotland."},
  {year:1713, event:"The Treat of Utrecht ends the War of Spanish Succession."},
  {year:1713, event:"Holy Roman Emperor Charles VI issues the Pragmantic Sanction."},
  {year:1733, event:"The Province of Georgia is founded by James Oglethorpe."},
  {year:1741, event:"Puritan Jonathan Edwards publishes Sinners in the Hands of an Angry God."},
  {year:1746, event:"Bonnie Prince Charlie loses the Battle of Culloden Moor."},
  {year:1750, event:"Johann Sebastian Bach dies of complications after eye surgery."},
  {year:1759, event:"Voltaire publishes Candide."},
  {year:1762, event:"Catherine the Great becomes Empress of Russia."},
  {year:1764, event:"The British Parliament passes the Sugar Act."},
  {year:1776, event:"Adam Smith publishes The Wealth of Nations."},
  {year:1781, event:"The Siege of Yorktown."},
  {year:1786, event:"Shays' Rebellion."},
  {year:1787, event:"Governor Arthur Phillip leads the First Fleet to colonize Australia."},
  {year:1788, event:"The United States Constitution is ratified."},
  {year:1789, event:"The Articles of Confederation is replaced."},
  {year:1789, event:"The Storming of the Bastille."},
  {year:1791, event:"Mozart dies at the age of 35."},
  {year:1793, event:"Eli Whitney invents the cotton gin."},
  {year:1794, event:"Maximilien Robespierre is executed."},
  {year:1804, event:"Lewis and Clark begin their journey west."},
  {year:1805, event:"The Battle of Trafalgar."},
  {year:1807, event:"America and Britain outlaw the slave trade."},
  {year:1815, event:"The Battle of Waterloo."},
  {year:1821, event:"Mexico gains independence from Spain."},
  {year:1826, event:"The Auspicious Event disbands the Janissary corps of the Ottoman Empire."},
  {year:1830, event:"The Indian Removal Act is passed and forces Native Americans onto the Trail of Tears."},
  {year:1834, event:"The Zollverein, or German Customs Union, is established."},
  {year:1836, event:"Samuel Colt invents the revolver."},
  {year:1846, event:"The Mexican-American War begins."},  
  {year:1846, event:"The British Corn Laws are repealed."},
  {year:1848, event:"The Seneca Falls Convention for women's rights."},
  {year:1848, event:"Karl Marx and Friedrich Engels publish The Communist Manifesto."},
  {year:1849, event:"The California Gold Rush."},
  {year:1852, event:"Uncle Tom's Cabin is published."},
  {year:1853, event:"Commodore Matthew Perry opens Japan."},
  {year:1853, event:"The Crimean War begins."},
  {year:1859, event:"Charles Darwin publishes On the Origin of Species."},
  {year:1860, event:"South Carolina secedes from the Union."},
  {year:1862, event:"The Battle of Antietam."},
  {year:1867, event:"Seward's Folly."},
  {year:1871, event:"Otto von Bismarck unifies all of Germany."},
  {year:1872, event:"Yellowstone National Park is created."},
  {year:1876, event:"The Battle of Little Bighorn."},
  {year:1876, event:"Alexander Graham Bell patents the telephone."},
  {year:1879, event:"Thomas Edison creates the first light bulb."},
  {year:1896, event:"The first modern Olympic Games are held in Athens."},
  {year:1901, event:"Edmund Barton becomes the first Prime Minister of Australia."},
  {year:1903, event:"The Wright Brothers' first flight in Kitty Hawk."},
  {year:1914, event:"Archduke Franz Ferdinand is assassinated."},
  {year:1915, event:"The sinking of the RMS Lusitania."},
  {year:1916, event:"The Battle of the Somme."},
  {year:1921, event:"Albert Einstein receives the Nobel Prize in Physics."},
  {year:1928, event:"All women over the age of 21 are given the right to vote in Britain."},
  {year:1928, event:"Alexander Fleming discovers Penicillin in a Petri dish."},
  {year:1940, event:"The Battle of Britain."},
  {year:1948, event:"Ireland breaks from the UK and becomes an independent state."},
  {year:1968, event:"The Tet Offensive."},
];
